# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .net UnitTests

on:
  push:
    branches: [ "main" ]
    
    paths:
    - src/**
    - Tests/EventBus.Tests/**
    
  pull_request:
    branches: [ "main" ]
        
    paths:
    - src/**
    - Tests/EventBus.Tests/**

jobs:
  BuildProjectForLinux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  
    - uses: ./.github/workflows/composite/build-test
      with:
        dotnet_version: 7.0.x
        project_path: src/EventBus
        tests_path: Tests/EventBus.Tests
